#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'ros-tutorial-NK','console_scripts','first_node_test'
__requires__ = 'ros-tutorial-NK'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('ros-tutorial-NK', 'console_scripts', 'first_node_test')()
    )
